name: Further tests Workflow

on:
  workflow_run:
    workflows: ["tests"]
    types:
      - completed
permissions: write-all

jobs:
  success:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v2

      - name: Download Image Tags
        uses: dawidd6/action-download-artifact@v2
        with:
          name: image_tags
          workflow: ci.yml
          # run_id: ${{ github.event.client_payload.runid }}
          run_id: ${{ github.event.workflow_run.id }}        
          path: ${{ github.workspace }}

      - name: Download Manifests
        uses: dawidd6/action-download-artifact@v2
        with:
          name: manifests
          workflow: ci.yml
          # run_id: ${{ github.event.client_payload.runid }}
          run_id: ${{ github.event.workflow_run.id }}        
          path: ${{ github.workspace }}
      - name: Read Image Tags
        run: |
          echo "IMAGE_TAG=$(cat ${{ github.workspace }}/IMAGE_TAG)" >> $GITHUB_ENV          
      - name: Generate Manifests
        run: |
          .github/workflows/utils/generate-manifests.sh ${{ github.workspace }}/manifests gen_manifests hld_only
        env:
            APP_BUILD_VERSION: ${{ env.IMAGE_TAG }}
            ORCHESTRATOR_PAT: ${{ secrets.ORCHESTRATOR_PAT }}
